In [1]:
#chapter - 4 Linear algebra 
#vector is arrow in space so ofcourse it would have direction and also would have some value
#in its intial form vector position of the tail in the cartisian plane is 0,0 

In [2]:
#vector 
v = [2,3]

In [3]:
v

[2, 3]

In [4]:
#making an vecto array usin thenumpy
import numpy as np  
vector = np.array([2,3])

In [5]:
vector

array([2, 3])

In [6]:
#vector do looks like numbers stored but we have to remember that its aspect of direction and other thing so that
#vector are not only number but have different roles in different aspects of the work 

In [7]:
#a three dimensional vector means three direction 
vector_3d = np.array([1,2,3])

In [8]:
vector_3d

array([1, 2, 3])

In [9]:
vector_5d = np.array([1,2,3,4,5])#it does look like simple plain array but when we visual we will see how 5 direction will make it work

In [10]:
#addition of  two vectors  
v = np.array([1,2,3])
w = np.array([-1,-2,-3])
v+w

array([0, 0, 0])

In [11]:
#adding two vector is easy but it is different when we see it in cartesian plane

In [12]:
#adding  vector is commutative means it does not matter in which  order i have to perform the function

In [13]:
#scaling of the vector 

In [14]:
#multplying or dividing the vector for scalling the vector 
v*2

array([2, 4, 6])

In [15]:
v*1/2

array([0.5, 1. , 1.5])

In [16]:
v*10000

array([10000, 20000, 30000])

In [17]:
v/10000

array([0.0001, 0.0002, 0.0003])

In [18]:
#manipulatinng the vector basically means that we are manipulating the data in simple terms 

In [19]:
#span and linear Dependence
#the whole space of the possible vectors are called span 
#when we have to vectors in the different direction we call it linearly  independent and it can have unlimited possible vectors

In [20]:
#the possible number of vectors become limited when they co existing on the same line it limits the possible number of vectors and they can't have many more than this 

In [21]:
#but why do we care if there are limited or not limited i am thinkinng this now lets me see what comes next story is going good 

In [22]:
#Linear transformation

In [23]:
#according to the matric - [2,3] 2 is in the position of the i hat and j is in the position of the j hat 

In [24]:
#they are individual as [2,0] and [0,3] if we see that on the graph 

In [25]:
#if we increase or decrease we have  to remember that other things like sampling or span or scalling is going to be different as weel 

In [26]:
#it addition vector will also increase since the increase in the its vector 

In [27]:
#we can't have curve or other things  in the linear algebra because it is called linear algebra

In [28]:
#that's the simple ideas we have got till now of vectors or algebra in the perspective of the data or scalling or whatever we call it 

In [29]:
#matrix multiplication in  the pandas 
from numpy import array
basis = array([[1,2],[2,3]])

In [30]:
basis 

array([[1, 2],
       [2, 3]])

In [32]:
prod = array([1,2])

In [ ]:
#mul