In [1]:
#chapter - 4 Linear algebra 
#vector is arrow in space so ofcourse it would have direction and also would have some value
#in its intial form vector position of the tail in the cartisian plane is 0,0 

In [2]:
#vector 
v = [2,3]

In [3]:
v

[2, 3]

In [4]:
#making an vecto array usin thenumpy
import numpy as np  
vector = np.array([2,3])

In [5]:
vector

array([2, 3])

In [6]:
#vector do looks like numbers stored but we have to remember that its aspect of direction and other thing so that
#vector are not only number but have different roles in different aspects of the work 

In [7]:
#a three dimensional vector means three direction 
vector_3d = np.array([1,2,3])

In [8]:
vector_3d

array([1, 2, 3])

In [10]:
vector_5d = np.array([1,2,3,4,5])#it does look like simple plain array but when we visual we will see how 5 direction will make it work

In [11]:
#addition of  two vectors  
v = np.array([1,2,3])
w = np.array([-1,-2,-3])
v+w

array([0, 0, 0])

In [12]:
#adding two vector is easy but it is different when we see it in cartesian plane

In [13]:
#adding  vector is commutative means it does not matter in which  order i have to perform the function

In [14]:
#scaling of the vector 

In [15]:
#multplying or dividing the vector for scalling the vector 
v*2

array([2, 4, 6])

In [16]:
v*1/2

array([0.5, 1. , 1.5])

In [17]:
v*10000

array([10000, 20000, 30000])

In [18]:
v/10000

array([0.0001, 0.0002, 0.0003])

In [19]:
#manipulatinng the vector basically means that we are manipulating the data in simple terms 