## Handling missing data in the pandas python 

In [1]:
#None pythonic missing data and Null pandas missing data 

In [2]:
import pandas as pd 
import numpy as np 

In [3]:
val1 = np.array([1,2,None,3,4])

In [4]:
val1

array([1, 2, None, 3, 4], dtype=object)

In [5]:
for dtype in ['object','int']:
    print(f'dtype = {dtype}')
    %timeit np.arange(1E6,dtype = dtype ).sum()
    print()

dtype = object
131 ms ± 7.76 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
6.89 ms ± 1.34 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [6]:
val1.sum()#such as thse aggregation function doesnotwork on differenet data types 

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [7]:
val2 = np.array([1,2,3,4,np.nan])

In [8]:
val2

array([ 1.,  2.,  3.,  4., nan])

In [9]:
val2.sum()

np.float64(nan)

In [10]:
val2.dtype

dtype('float64')

In [11]:
#Nan is like virus it affects other values also that is other than in the case 

In [12]:
#Nan we can perform function while nan is present 

In [13]:
#for ignoring the nan itself we can perform aggregate 

In [14]:
np.nansum(val2)

np.float64(10.0)

In [15]:
np.nanmin(val2)

np.float64(1.0)

In [16]:
np.nanmax(val2)

np.float64(4.0)

In [17]:
np.nanargmax(val2)

np.int64(3)

In [18]:
#so we can perform function using numpy in this case 

In [19]:
val1

array([1, 2, None, 3, 4], dtype=object)

In [20]:
val1[2] = 1

In [21]:
val1

array([1, 2, 1, 3, 4], dtype=object)

In [22]:
val1 

array([1, 2, 1, 3, 4], dtype=object)

In [23]:
val1.dtype

dtype('O')

In [24]:
x = pd.Series(np.arange(2,dtype = int))

In [25]:
x

0    0
1    1
dtype: int64

In [26]:
x[0] = None

In [27]:
x

0    NaN
1    1.0
dtype: float64

In [28]:
#so here we can see that it has been changing the data type to the float so we can expect that nan is a float values that why it is changing the dtype of the pandas series 

In [29]:
#so nan dont change the data type of the floats and objects 

In [30]:
#operatoin on the null values 

In [31]:
data = pd.Series([1, np.nan, 'hello', None])

In [32]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [33]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [34]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [35]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [36]:
data[data.isnull()]

1     NaN
3    None
dtype: object

In [37]:
#for dropping the na values 
data.dropna()


0        1
2    hello
dtype: object

In [38]:
#for filling the na values in the data 
data.fillna(0)

0        1
1        0
2    hello
3        0
dtype: object

In [39]:
df = pd.DataFrame([[1, np.nan, 2],
[2, 3, 5],
[np.nan, 4, 6]])

In [40]:
df

,0,1,2
0,1.0,NaN,2
1,2.0,3.0,5
2,NaN,4.0,6


In [41]:
#here we ccnot not drop one value it will either drop the row or full colunmns

In [42]:
df.dropna()

,0,1,2
1,2.0,3.0,5


In [43]:
#dropping na value in the columns wise 
df.dropna(axis = 1)

,2
0,2
1,5
2,6


In [44]:
#different ways to filling the values 
df.fillna(method = 'ffill')

C:\Users\Monu Verma\AppData\Local\Temp\ipykernel_22216\1544481526.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill')


,0,1,2
0,1.0,NaN,2
1,2.0,3.0,5
2,2.0,4.0,6


In [45]:
df.fillna('ffill')

,0,1,2
0,1.0,ffill,2
1,2.0,3.0,5
2,ffill,4.0,6


In [46]:
df.ffill()

,0,1,2
0,1.0,NaN,2
1,2.0,3.0,5
2,2.0,4.0,6


In [47]:
df.fillna(0)

,0,1,2
0,1.0,0.0,2
1,2.0,3.0,5
2,0.0,4.0,6


In [48]:
df.bfill()

,0,1,2
0,1.0,3.0,2
1,2.0,3.0,5
2,NaN,4.0,6


In [49]:
df

,0,1,2
0,1.0,NaN,2
1,2.0,3.0,5
2,NaN,4.0,6


In [50]:
df.bfill(axis = 1)

,0,1,2
0,1.0,2.0,2.0
1,2.0,3.0,5.0
2,4.0,4.0,6.0


In [51]:
df.bfill()

,0,1,2
0,1.0,3.0,2
1,2.0,3.0,5
2,NaN,4.0,6


In [52]:
df.ffill(axis=1)

,0,1,2
0,1.0,1.0,2.0
1,2.0,3.0,5.0
2,NaN,4.0,6.0


In [53]:
df.fillna(0.000)

,0,1,2
0,1.0,0.0,2
1,2.0,3.0,5
2,0.0,4.0,6
