# Boolean array masking 

In [1]:
import numpy as np 

In [2]:
#creating a 2d array 
x = np.random.RandomState()
y = x.randint(10,size=(3,3))

In [3]:
y

array([[9, 1, 0],
       [6, 8, 3],
       [8, 0, 9]], dtype=int32)

In [4]:
y

array([[9, 1, 0],
       [6, 8, 3],
       [8, 0, 9]], dtype=int32)

In [5]:
y

array([[9, 1, 0],
       [6, 8, 3],
       [8, 0, 9]], dtype=int32)

In [6]:
#Random state is achieved 

In [7]:
#doing boolean masking and also making an new conditoned array based on that

In [8]:
z = y[y>3].copy()

In [9]:
z

array([9, 6, 8, 8, 9], dtype=int32)

In [10]:
z[:] = 0

In [11]:
z

array([0, 0, 0, 0, 0], dtype=int32)

In [12]:
y

array([[9, 1, 0],
       [6, 8, 3],
       [8, 0, 9]], dtype=int32)

In [13]:
bool(41)

True

In [14]:
bin(41)

'0b101001'

In [15]:
bin(0)

'0b0'

In [16]:
bool(0)

False

In [17]:
a = np.array([1,1,1,1,0,1],dtype=bool)
b = np.array([0,0,0,2,0,1],dtype=bool)
a|b

array([ True,  True,  True,  True, False,  True])

In [18]:
a&b

array([False, False, False,  True, False,  True])

In [19]:
a or b

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
a and b

In [ ]:
#so here we noticed that it is giving the error using or and 'and' as it  perform on the etire object rather than performing on the individual bits or bytes
#| and &  this is used to perform for using this functions

## Fancy indexing in numpy 

In [34]:
#let's generate a random array 
rand = np.random.RandomState(42)#just 42 RANDOM STATE  blaah just 42 is joke 
a = rand.randint(100, size = 10)

In [35]:
a

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74], dtype=int32)

In [36]:
#normal indexing  
a[0]

np.int32(51)

In [37]:
a[2]

np.int32(14)

In [38]:
inc = [2,3,4]
a[inc]

array([14, 71, 60], dtype=int32)

In [39]:
#or something like this 
[a[0],a[1]]

[np.int32(51), np.int32(92)]

In [40]:
#here comes fancy indexing 

In [43]:
b = np.array([[2,3],[4,5]])
a[b]

array([[14, 71],
       [60, 20]], dtype=int32)

In [44]:
ind = np.array([[2,3,4],
    [4,5,6],
    [1,6,2]])

In [45]:
a[ind]

array([[14, 71, 60],
       [60, 20, 82],
       [92, 82, 14]], dtype=int32)

In [46]:
#this is cool because here we are not generating array for the ind only it is an actualy array and we are doing indexing on that actual array usingn other data 

In [47]:
#combined indexing 
#in combined indexinng we are going to use both indexking and fancy indexkinng 


In [50]:
#lets generate an array 

a = np.arange(9).reshape(3,3)
a 


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
a[2,[1,2,0]]+a[0,[0,1,2]]# type of mixing the broadcasting  , normal indexing, fancy indexing 

array([7, 9, 8])

In [57]:
a[:,[1,2,0]]#indexes with slices 

array([[1, 2, 0],
       [4, 5, 3],
       [7, 8, 6]])

In [58]:
a[1:3 ,[0,1,2]]

array([[3, 4, 5],
       [6, 7, 8]])