# Boolean array masking 

In [1]:
import numpy as np 

In [3]:
#creating a 2d array 
x = np.random.RandomState()
y = x.randint(10,size=(3,3))

In [4]:
y

array([[1, 3, 1],
       [5, 6, 3],
       [2, 4, 9]], dtype=int32)

In [5]:
y

array([[1, 3, 1],
       [5, 6, 3],
       [2, 4, 9]], dtype=int32)

In [6]:
y

array([[1, 3, 1],
       [5, 6, 3],
       [2, 4, 9]], dtype=int32)

In [8]:
#Random state is achieved 

In [9]:
#doing boolean masking and also making an new conditoned array based on that

In [17]:
z = y[y>3].copy()

In [18]:
z

array([5, 6, 4, 9], dtype=int32)

In [19]:
z[:] = 0

In [20]:
z

array([0, 0, 0, 0], dtype=int32)

In [21]:
y

array([[1, 3, 1],
       [5, 6, 3],
       [2, 4, 9]], dtype=int32)

In [22]:
bool(41)

True

In [25]:
bin(41)

'0b101001'

In [26]:
bin(0)

'0b0'

In [27]:
bool(0)

False

In [28]:
a = np.array([1,1,1,1,0,1],dtype=bool)
b = np.array([0,0,0,2,0,1],dtype=bool)
a|b

array([ True,  True,  True,  True, False,  True])

In [29]:
a&b

array([False, False, False,  True, False,  True])

In [30]:
a or b

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [31]:
a and b

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [34]:
#so here we noticed that it is giving the error using or and 'and' as it  perform on the etire object rather than performing on the individual bits or bytes
#| and &  this is used to perform for using this functions