### Broadcasting in Numpy

In [1]:
#adding things colums wise accoriding to the elements 
import numpy as np 
a = np.array([0,1,2])
b = np.array([1,2,3])
a+b

array([1, 3, 5])

In [2]:
# We can think of this as an operation that stretches or duplicates the value 5 into the
# array [5, 5, 5], and adds the results. The advantage of NumPy’s broadcasting is that
# this duplication of values does not actually take place, but it is a useful mental model
# as we think about broadcasting.

In [3]:
c = np.ones((3,3))

In [4]:
a+c

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [5]:
#so here one dimensional array is stretched over the 3 dimensinal arrays and have done the computaion according to it 

In [6]:
x = np.arange(3)
y = np.arange(3)[:,np.newaxis]

In [7]:
x

array([0, 1, 2])

In [8]:
y

array([[0],
       [1],
       [2]])

In [9]:
x+y#here we have stretched both the a and b to match the actual value's 

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [10]:
#it is adding the columns and row wise 

In [11]:
#so today we are gonna study the  broadcasting 

In [14]:
#example 1 for the broadcasting rules 


x = np.ones((2,3))
y = np.arange(3)

In [15]:
x.shape

(2, 3)

In [16]:
y.shape

(3,)

In [19]:
'so according the rules of the broadcasting the arrays with shape 1 dimenstional will fit according the array of the other 2 dimensional array'

'so according the rules of the broadcasting the arrays with shape 1 dimenstional will fit according the array of the other 2 dimensional array'

In [20]:
# so here it will change (1,3) to (2,3)
x+y

array([[1., 2., 3.],
       [1., 2., 3.]])

In [22]:
#example - 2 
a = np.arange(3).reshape(3,1)
b = np.arange(3)


In [23]:
#so here a shape will change from 3,1 to (3,3) because to fit to accoring to the array second 
#so array b shape will change form 1,3 to (3,3) becuase to fit to accroding to array of the other array that has being broadcating 


In [24]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [25]:
#example - 3

In [27]:
p = np.ones((3,2))
q = np.arange(3)


In [28]:
#so here it will give error becuase there is one column missing inthe the p because to broadcaste over here there will 
#hence , it can't be broadcasted here

In [29]:
p+q

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [31]:
#solving the problem
r = p.copy()

In [38]:
#right side padding 
r = r.reshape(2,3)

In [39]:
r+q

array([[1., 2., 3.],
       [1., 2., 3.]])

In [40]:
#so the problem is solved by changing the shape of the array accorind the shape required to fit in this |

In [37]:
#this broadcasting is also called padding the values in the left side to match the shape of the arrays

In [43]:
#left side padding of the array
#using the newaxis formula to do the left side padding of the array 
p+q[:,np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

In [44]:
#--- BROADCASTING CAN BE APPLIED TO ANY BINARY FUNCTION INCLUDING LOG EXP

In [48]:
np.logaddexp(p,q[: ,np.newaxis])

array([[1.31326169, 1.31326169],
       [1.69314718, 1.69314718],
       [2.31326169, 2.31326169]])

In [49]:
p*q[:,np.newaxis]

array([[0., 0.],
       [1., 1.],
       [2., 2.]])

In [51]:
p/q[:,np.newaxis]

C:\Users\Monu Verma\AppData\Local\Temp\ipykernel_2460\2324743992.py:1: RuntimeWarning: divide by zero encountered in divide
  p/q[:,np.newaxis]


array([[inf, inf],
       [1. , 1. ],
       [0.5, 0.5]])

# Broadcasting in practise


In [56]:
#centering an array 
X = np.random.random((10,3))

In [60]:
#MEAN OF THE ARRAY X 
XMEAN = np.mean(X,axis=0)

In [61]:
XMEAN

array([0.46510197, 0.53800079, 0.40703845])

In [62]:
#centering the array by subtracting the array by Xmean 
X_centered = X-XMEAN

In [67]:
X_centered.mean(axis=0)

array([-6.10622664e-17,  5.55111512e-17, -5.55111512e-17])