### Computation on NumPy Arrays: Universal Functions

In [1]:
#lets caluculate the reciprocal of the numbers

In [3]:

import numpy as np 
np.random.seed(0)

def computing_reciprocal(values):
    ouput = np.empty(len(values))
    for i in range (len(values)):
        ouput[i] = 1/values[i]

    return ouput

values = np.random.randint(1,11,size = 5)
computing_reciprocal(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [6]:
big_array = np.random.randint(1,100,size=10000)

%timeit computing_reciprocal(big_array)

4.41 ms ± 242 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
#python function are too slow to caluculate anything so we will use numpy computation funcs
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [9]:
x = np.full((3,3),1)
x

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [10]:
x*(1-1)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:
x*(2-(-3))

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [12]:
#computioon in numpy  is very effiecence in the respect to anythin like python funtion 

In [24]:

%timeit 1/np.random.randint(1,10,size=10000000)
1/np.random.randint(1,100,size=10000000)[1:1000]

424 ms ± 33.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


array([0.01369863, 0.03225806, 0.01123596, 0.01369863, 0.09090909,
       0.01785714, 0.01351351, 0.01123596, 0.03571429, 0.01587302,
       0.01515152, 0.05555556, 0.03448276, 0.14285714, 0.01282051,
       0.03703704, 0.0125    , 0.01851852, 0.01176471, 0.01492537,
       0.03703704, 0.03333333, 0.025     , 0.11111111, 0.02222222,
       0.01123596, 0.1       , 0.04761905, 0.01923077, 0.16666667,
       0.02857143, 0.01818182, 0.02      , 0.01666667, 0.01428571,
       0.02173913, 0.01369863, 0.01086957, 0.02083333, 0.01754386,
       0.02439024, 0.01149425, 0.04166667, 0.01020408, 0.06666667,
       0.02325581, 0.04347826, 0.01923077, 0.01190476, 0.01162791,
       0.01298701, 0.03225806, 0.01388889, 0.33333333, 0.01369863,
       0.01282051, 0.02325581, 0.01190476, 0.01587302, 0.07692308,
       0.01149425, 0.01449275, 0.01851852, 0.01785714, 0.05555556,
       0.01785714, 0.04347826, 0.02173913, 0.07692308, 0.05555556,
       0.07142857, 0.01388889, 0.2       , 0.02040816, 0.01282

In [26]:
#type of ufuncs in numpy 
"binary ufuncs"#single inputs  
"unary ufuncs"#more than one inputs

'unary ufuncs'

In [27]:
#arithmatics computation in the numpy 

In [37]:
arth = np.arange(1,101)#100 different numbers showed as x 

print(f'x+5= {arth+5}\nx-5 ={arth-5}\nx*5={arth*5}\n')
arth//5
arth/0

x+5= [  6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23
  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41
  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59
  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95
  96  97  98  99 100 101 102 103 104 105]
x-5 =[-4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19
 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95]
x*5=[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180
 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265 270
 275 280 285 290 295 300 305 310 315 320 325 330 335 3

C:\Users\Monu Verma\AppData\Local\Temp\ipykernel_42924\3263849461.py:5: RuntimeWarning: divide by zero encountered in divide
  arth/0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf])