### Broadcasting in Numpy

In [15]:
#adding things colums wise accoriding to the elements 
import numpy as np 
a = np.array([0,1,2])
b = np.array([1,2,3])
a+b

array([1, 3, 5])

In [16]:
# We can think of this as an operation that stretches or duplicates the value 5 into the
# array [5, 5, 5], and adds the results. The advantage of NumPy’s broadcasting is that
# this duplication of values does not actually take place, but it is a useful mental model
# as we think about broadcasting.

In [17]:
c = np.ones((3,3))

In [18]:
a+c

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [14]:
#so here one dimensional array is stretched over the 3 dimensinal arrays and have done the computaion according to it 

In [37]:
x = np.arange(3)
y = np.arange(3)[:,np.newaxis]

In [38]:
x

array([0, 1, 2])

In [39]:
y

array([[0],
       [1],
       [2]])

In [42]:
x+y#here we have stretched both the a and b to match the actual value's 

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [43]:
#it is adding the columns and row wise 