In [1]:
#modifying Value with fancy indexing 


In [5]:
import numpy as np 
x = np.arange(10)
a = [2,3,4,5]
x[a] = 0 #it is a way of modying multiple value at once 
x

array([0, 1, 0, 0, 0, 0, 6, 7, 8, 9])

In [11]:
y = np.zeros(10)
y[[0,0]] = [4,6]
y#here we can see that 4 is not in the result it is simply means that first it becomes 4 then i comes to 6 and becomes 6 thats why it is not  4

array([6., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
z = np.zeros(10)
i = [2,3,3,4,4,4]
z[i] += 1 #here we were imagening that it will give 1 , 2, 3 but we were wrong it is just performing onnn bases of i 
z

array([0., 0., 1., 1., 1., 0., 0., 0., 0., 0.])

In [23]:
#to perform it correctly 
np.add.at(z,i,1)
z

array([0., 0., 3., 5., 7., 0., 0., 0., 0., 0.])

## Using this to binning the data using the modification using fancy indexing 
