### Numpy 

In [23]:
import numpy as np 
np.__version__

'2.3.5'

In [26]:
result = 0 
for i in range(1000):
    result+=1


In [27]:
x = 4 
x = "four"

In [29]:
#python integer is more than just a interger this is what it is behind the interface
('''struct _longobject {
long ob_refcnt;,
PyTypeObject *ob_type;,
size_t ob_size;,
long ob_digit[1];,
};''')

'struct _longobject {\nlong ob_refcnt;,\nPyTypeObject *ob_type;,\nsize_t ob_size;,\nlong ob_digit[1];,\n};'

In [37]:
#python list is more than just a list 
L = list(range(10))
L


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [38]:
type(L[0]) #finding the type of the object that is in the List 

int

In [42]:
#string objects List 
L2 = [str(c) for c in L]
L2


['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [45]:
L3 = [int(c) for c in L2]
L3

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
L4 = ['True',"False",1,3,'SET']
print([type(objects) for objects in L4])

[<class 'str'>, <class 'str'>, <class 'int'>, <class 'int'>, <class 'str'>]


In [1]:
L5 = [items for items in range(1) ]
L5


[0]

In [71]:
import array
array = array.array('i',L)#here i indeicates that content are in the integers

In [72]:
array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
type(_)

array.array

In [74]:
type(__)

array.array

In [77]:
array??

Type:        array
String form: array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Length:      10
Docstring:  
array(typecode [, initializer]) -> array

Return a new array whose items are restricted by typecode, and
initialized from the optional initializer value, which must be a list,
string or iterable over elements of the appropriate type.

Arrays represent basic values and behave very much like lists, except
the type of objects stored in them is constrained. The type is specified
at object creation time by using a type code, which is a single character.
The following type codes are defined:

    Type code   C Type             Minimum size in bytes
    'b'         signed integer     1
    'B'         unsigned integer   1
    'u'         Unicode character  2 (see note)
    'h'         signed integer     2
    'H'         unsigned integer   2
    'i'         signed integer     2
    'I'         unsigned integer   2
    'l'         signed integer     4
    'L'         unsigned integer   4
   

In [3]:
import numpy as np 
np.array([1,2,32432,2,43,4,3])

array([    1,     2, 32432,     2,    43,     4,     3])

In [7]:
a = np.array([1,2,3,4.5,343,3] ,dtype='object')

In [11]:
np.array([range(i,i+3) for i in [2,3,4]])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [12]:
a = np.array([1,2,3,4.5,343,3] ,dtype='float32')

In [15]:
type(a)

numpy.ndarray

### Creating a array from the scratch 

In [18]:
np.zeros(22,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.zeros((2,2), dtype= int)

array([[0, 0],
       [0, 0]])

In [21]:
np.zeros ((23,23), dtype= int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [22]:
np.ones((43,1),dtype=int)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [23]:
np.ones((99,99),dtype=int)

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], shape=(99, 99))

In [31]:
#create the numpy array of the given dimension of given number
np.full((12,12),23)

array([[23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23]])

In [29]:
np.full((2,2),2)

array([[2, 2],
       [2, 2]])

In [35]:
np.arange(0,20,0.01)#give the array from 0 to 20 with the gap of 0.01

array([0.000e+00, 1.000e-02, 2.000e-02, ..., 1.997e+01, 1.998e+01,
       1.999e+01], shape=(2000,))

In [37]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [38]:
np.linspace(0,2,2)

array([0., 2.])

In [41]:
np.random.random((3,3))

array([[0.72938335, 0.64615113, 0.84838984],
       [0.38974173, 0.86253282, 0.28343857],
       [0.6756532 , 0.10467694, 0.41441718]])

In [44]:
np.full((3,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [48]:
np.random.normal(3,4,(1,2))

array([[1.97377082, 3.10354536]])

In [46]:
np.random.normal(1,2,(33,33))

array([[ 3.19516365,  2.14212981, -1.82613836, ...,  1.23120226,
         0.69517034, -3.34125735],
       [-1.83904333,  2.04388946,  0.25185585, ...,  0.6044556 ,
         5.08109369,  0.14514825],
       [ 4.83143829,  3.42063132, -1.79989601, ..., -0.31393186,
         0.72777628,  4.24727738],
       ...,
       [ 2.72501428,  1.95407105,  1.07404076, ..., -2.96018114,
        -0.07219828,  3.03940342],
       [ 2.10889536, -0.51172425, -1.21865841, ..., -2.21068266,
         3.86886179,  1.93299695],
       [ 0.98103045, -1.28553179,  2.51825005, ...,  1.47049683,
         1.61793475,  0.0986044 ]], shape=(33, 33))

In [50]:
np.random.randint(0,1000,(10,10))#taking a range of 0 to 1000 then mkaed a random array out of it 

array([[918, 328, 695, 899, 238, 638, 226, 878, 391, 651],
       [399, 680, 554, 840, 717, 913, 348, 151, 265,  74],
       [559, 492, 172, 643, 324, 257, 693,  26, 507, 450],
       [319, 701, 244, 564, 986, 132,  62, 211, 663, 170],
       [610, 456, 395, 427, 941, 492, 670, 638, 299, 367],
       [313, 684, 970, 120, 197, 303, 911,  41, 787, 966],
       [518, 340, 716, 513, 983,  61, 226, 762, 127,  88],
       [ 65, 574, 917, 463, 330, 237, 238, 429, 147,  21],
       [876, 161, 437, 276, 458, 767,  68, 295, 716, 317],
       [253, 428, 432, 295, 956, 742, 525, 275, 919, 211]], dtype=int32)

In [53]:
np.random.randint(1,2,(2,2),dtype=int)

array([[1, 1],
       [1, 1]], dtype=int32)

In [55]:
np.eye(9)#create an indenity matrix of the 9*9 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [56]:
np.random?

Type:        module
String form: <module 'numpy.random' from 'C:\\Users\\Monu Verma\\Searches\\New folder\\Lib\\site-packages\\numpy\\random\\__init__.py'>
File:        c:\users\monu verma\searches\new folder\lib\site-packages\numpy\random\__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

=============================================

In [57]:
np.random.randint?

Signature: np.random.randint(low, high=None, size=None, dtype=<class 'int'>)
Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-lik

In [58]:
np.random.random?

Signature: np.random.random(size=None)
Docstring:
random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.
Type:      method

In [59]:
np.empty?

Docstring:
empty(shape, dtype=float, order='C', *, device=None, like=None)

Return a new array of given shape and type, without initializing entries.

Parameters
----------
shape : int or tuple of int
    Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    Desired output data-type for the array, e.g, `numpy.int8`. Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
device : str, optional
    The device on which to place the created array. Default: ``None``.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it

In [60]:
_

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [61]:
np.empty(3)

array([8.40433006e-312, 0.00000000e+000, 6.47591605e-319])