In [3]:
import numpy as np 

In [4]:
x = np.random.randint(10,size=(3,4))

In [5]:
x

array([[9, 5, 3, 1],
       [7, 6, 7, 0],
       [3, 2, 8, 8]], dtype=int32)

In [6]:
#x[start:stop:step]

In [7]:
x1 = np.arange(10)

In [8]:
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x1[:5]

array([0, 1, 2, 3, 4])

In [10]:
x1[5:]

array([5, 6, 7, 8, 9])

In [11]:
x1[6:8]

array([6, 7])

In [13]:
x1[0:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x1[::2]#every other elements starting at 0 

array([0, 2, 4, 6, 8])

In [30]:
x1[2::1]#every other elements with the starting 2 and aslo with gap between them is 2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [20]:
x1[1::2]

array([1, 3, 5, 7, 9])

In [31]:
x2 = np.arange(100)

In [32]:
x2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [33]:
x2[1::10]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [35]:
x2[::10]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])