### Numpy 

In [23]:
import numpy as np 
np.__version__

'2.3.5'

In [26]:
result = 0 
for i in range(1000):
    result+=1


In [27]:
x = 4 
x = "four"

In [29]:
#python integer is more than just a interger this is what it is behind the interface
('''struct _longobject {
long ob_refcnt;,
PyTypeObject *ob_type;,
size_t ob_size;,
long ob_digit[1];,
};''')

'struct _longobject {\nlong ob_refcnt;,\nPyTypeObject *ob_type;,\nsize_t ob_size;,\nlong ob_digit[1];,\n};'

In [37]:
#python list is more than just a list 
L = list(range(10))
L


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [38]:
type(L[0]) #finding the type of the object that is in the List 

int

In [42]:
#string objects List 
L2 = [str(c) for c in L]
L2


['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [45]:
L3 = [int(c) for c in L2]
L3

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
L4 = ['True',"False",1,3,'SET']
print([type(objects) for objects in L4])

[<class 'str'>, <class 'str'>, <class 'int'>, <class 'int'>, <class 'str'>]


In [1]:
L5 = [items for items in range(1) ]
L5


[0]

In [71]:
import array
array = array.array('i',L)#here i indeicates that content are in the integers

In [72]:
array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
type(_)

array.array

In [74]:
type(__)

array.array

In [77]:
array??

Type:        array
String form: array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Length:      10
Docstring:  
array(typecode [, initializer]) -> array

Return a new array whose items are restricted by typecode, and
initialized from the optional initializer value, which must be a list,
string or iterable over elements of the appropriate type.

Arrays represent basic values and behave very much like lists, except
the type of objects stored in them is constrained. The type is specified
at object creation time by using a type code, which is a single character.
The following type codes are defined:

    Type code   C Type             Minimum size in bytes
    'b'         signed integer     1
    'B'         unsigned integer   1
    'u'         Unicode character  2 (see note)
    'h'         signed integer     2
    'H'         unsigned integer   2
    'i'         signed integer     2
    'I'         unsigned integer   2
    'l'         signed integer     4
    'L'         unsigned integer   4
   

In [3]:
import numpy as np 
np.array([1,2,32432,2,43,4,3])

array([    1,     2, 32432,     2,    43,     4,     3])

In [7]:
a = np.array([1,2,3,4.5,343,3] ,dtype='object')

In [11]:
np.array([range(i,i+3) for i in [2,3,4]])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [12]:
a = np.array([1,2,3,4.5,343,3] ,dtype='float32')

In [15]:
type(a)

numpy.ndarray

### Creating a array from the scratch 

In [18]:
np.zeros(22,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.zeros((2,2), dtype= int)

array([[0, 0],
       [0, 0]])

In [21]:
np.zeros ((23,23), dtype= int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [22]:
np.ones((43,1),dtype=int)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [23]:
np.ones((99,99),dtype=int)

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], shape=(99, 99))

In [31]:
#create the numpy array of the given dimension of given number
np.full((12,12),23)

array([[23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23]])

In [29]:
np.full((2,2),2)

array([[2, 2],
       [2, 2]])

In [35]:
np.arange(0,20,0.01)#give the array from 0 to 20 with the gap of 0.01

array([0.000e+00, 1.000e-02, 2.000e-02, ..., 1.997e+01, 1.998e+01,
       1.999e+01], shape=(2000,))

In [37]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [38]:
np.linspace(0,2,2)

array([0., 2.])

In [41]:
np.random.random((3,3))

array([[0.72938335, 0.64615113, 0.84838984],
       [0.38974173, 0.86253282, 0.28343857],
       [0.6756532 , 0.10467694, 0.41441718]])

In [43]:
np.full((3,3),np.random.normal((3,3)))

ValueError: could not broadcast input array from shape (2,) into shape (3,3)