In [1]:
import numpy as np 

In [2]:
x = np.random.randint(10,size =(3,10))

In [3]:
x

array([[4, 1, 7, 9, 8, 7, 1, 5, 5, 9],
       [4, 4, 4, 3, 2, 3, 7, 2, 0, 3],
       [7, 1, 6, 7, 3, 4, 7, 2, 8, 0]], dtype=int32)

In [4]:
x[:1,:2]

array([[4, 1]], dtype=int32)

In [5]:
x[:2,:3]

array([[4, 1, 7],
       [4, 4, 4]], dtype=int32)

In [6]:
x[:3,:1]

array([[4],
       [4],
       [7]], dtype=int32)

In [7]:
x[:1,:1]

array([[4]], dtype=int32)

In [8]:
x[:,:]

array([[4, 1, 7, 9, 8, 7, 1, 5, 5, 9],
       [4, 4, 4, 3, 2, 3, 7, 2, 0, 3],
       [7, 1, 6, 7, 3, 4, 7, 2, 8, 0]], dtype=int32)

In [9]:
x[:,::2]

array([[4, 7, 8, 1, 5],
       [4, 4, 2, 7, 0],
       [7, 6, 3, 7, 8]], dtype=int32)

In [10]:
x[:,::-2]

array([[9, 5, 7, 9, 1],
       [3, 2, 3, 3, 4],
       [0, 2, 4, 7, 1]], dtype=int32)

In [11]:
x[:,::-2]

array([[9, 5, 7, 9, 1],
       [3, 2, 3, 3, 4],
       [0, 2, 4, 7, 1]], dtype=int32)

In [12]:
x[2:,::]

array([[7, 1, 6, 7, 3, 4, 7, 2, 8, 0]], dtype=int32)

In [13]:
"Note - The array do not written the  copy but changing the slicing will change the orignal data so use copy method "

'Note - The array do not written the  copy but changing the slicing will change the orignal data so use copy method '

In [14]:
x_2 =x[0,:].copy()

In [15]:
x

array([[4, 1, 7, 9, 8, 7, 1, 5, 5, 9],
       [4, 4, 4, 3, 2, 3, 7, 2, 0, 3],
       [7, 1, 6, 7, 3, 4, 7, 2, 8, 0]], dtype=int32)

In [16]:
x_3 = x.copy()

In [17]:
x_3

array([[4, 1, 7, 9, 8, 7, 1, 5, 5, 9],
       [4, 4, 4, 3, 2, 3, 7, 2, 0, 3],
       [7, 1, 6, 7, 3, 4, 7, 2, 8, 0]], dtype=int32)

In [18]:
x_3[0,:] = 1

In [19]:
x_3[0,:]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

### Reshaping the arrays 

In [20]:
x = np.arange(1,10).reshape(3,3)

In [21]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
x_2 = np.arange(1,15).reshape(2,7)#elements must be fittable in the  give array size 

In [23]:
x_2

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [24]:
x_1 = np.eye(3,4).reshape(1,12)
x_1

array([[1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.]])

In [25]:
#changing the dimension of the array 
x = np.arange(1,13)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
x_column_matrix = x.reshape(12,1).copy()

In [27]:
x_column_matrix

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [28]:
x_2d = x.copy().reshape(2,6)

In [29]:
x_2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [30]:
x_3d = x.copy().reshape(3,4)

In [31]:
x_3d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
x_4d = x.copy().reshape(6,2)

In [33]:
x_4d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [34]:
y = np.array([[1,2,3],[1,2,3]])

In [35]:
y

array([[1, 2, 3],
       [1, 2, 3]])

In [36]:
y[:,np.newaxis]

array([[[1, 2, 3]],

       [[1, 2, 3]]])

In [37]:
y[np.newaxis,:]

array([[[1, 2, 3],
        [1, 2, 3]]])

In [38]:
#note point - note point is that np.newaxis work only to make row matrix and column matric reshape is a flexible method to do the things 

### Array Concatenation and Splitting
All of the preceding routines worked on single arrays. It’s also possible to combine
multiple arrays into one, and to conversely split a single array into multiple arrays.

In [39]:
x1 = np.random.randint(10,size =(2,3))
x2 = np.random.randint(10,size =(2,3))
x3 = np.random.randint(19000,size =(2,3))

In [40]:
#concatenating multiple array one can be at any limit 
print(np.concatenate([x1,x2,x3,x2,x3,x2,x1,x1]))#it is concatenated in the firsts exis which is a defalut exis by far 

[[    7     9     2]
 [    3     2     5]
 [    6     7     0]
 [    9     0     9]
 [14347 14087  8468]
 [16916 17032 15363]
 [    6     7     0]
 [    9     0     9]
 [14347 14087  8468]
 [16916 17032 15363]
 [    6     7     0]
 [    9     0     9]
 [    7     9     2]
 [    3     2     5]
 [    7     9     2]
 [    3     2     5]]


In [41]:
print(np.concatenate([x1,x2,x3,x2,x3,x2,x1,x1],axis=1))#concatenating in the axis = 1 

[[    7     9     2     6     7     0 14347 14087  8468     6     7     0
  14347 14087  8468     6     7     0     7     9     2     7     9     2]
 [    3     2     5     9     0     9 16916 17032 15363     9     0     9
  16916 17032 15363     9     0     9     3     2     5     3     2     5]]


In [42]:
#axis 0 means it is going downward - vertically 
#axis 1 means it is going sidebyside - horizontal 

In [43]:
#vstacking in numpy means vertical stacking 
a = np.arange(1,4)
a1 = np.random.randint(4,size=(2,3))

In [44]:
%xmode Verbose
print(np.vstack([a,a1]))

Exception reporting mode: Verbose
[[1 2 3]
 [2 3 1]
 [2 0 3]]


In [45]:
_

array([[[1, 2, 3],
        [1, 2, 3]]])

In [46]:
__

array([[[1, 2, 3],
        [1, 2, 3]]])

In [47]:
a2 = np.array([[99],[99]])

In [48]:
#hstact means stacking it horizontally and can be said that filling the value into available arrays 
print(np.hstack([a2,a1]))

[[99  2  3  1]
 [99  2  0  3]]


In [49]:
#note - dimension should be mathing when this function is applie either it will give error 

In [50]:
#splliting of arrays 

In [87]:
x = [1,2,3,4,5,6,7,8]
x1,x2,x3 = np.split(x,(4,4))

In [88]:
x1,x2,x3

(array([1, 2, 3, 4]), array([], dtype=int64), array([5, 6, 7, 8]))

In [89]:
np.split?

Signature:       np.split(ary, indices_or_sections, axis=0)
Call signature:  np.split(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function split at 0x000001B177D7E340>
File:            c:\users\monu verma\searches\new folder\lib\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split an array into multiple sub-arrays as views into `ary`.

Parameters
----------
ary : ndarray
    Array to be divided into sub-arrays.
indices_or_sections : int or 1-D array
    If `indices_or_sections` is an integer, N, the array will be divided
    into N equal arrays along `axis`.  If such a split is not possible,
    an error is raised.

    If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[2, 3]`` would, for ``axis=0``, result in

    - ary[:2]
    - ary[2:3]
    - ary[3:]

    If an index exceeds the dimension of the array along `axis`,
    an empty sub-array is ret