In [2]:
#complex form of the absolute value 
import numpy as np 
a = np.array([3-4j,4-5j,6-4j])
abs(a)

array([5.        , 6.40312424, 7.21110255])

In [9]:
b = np.arange(-10,-3)
abs(b)

array([10,  9,  8,  7,  6,  5,  4])

In [14]:
abs(np.random.randint(-20,-1,size=(3,3)))#giving the absolute value of everything 

array([[10,  4,  7],
       [ 6, 20,  7],
       [10, 13, 11]], dtype=int32)

In [18]:
for i in range(1,10):
    print(np.random.randint(i,i+1,size=(3,3)))

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[8 8 8]
 [8 8 8]
 [8 8 8]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]


### Trignometric functions

In [19]:
c = np.linspace(0,np.pi,10)

In [20]:
c

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

In [27]:
np.sin(c)
np.cos(c)

array([ 1.        ,  0.93969262,  0.76604444,  0.5       ,  0.17364818,
       -0.17364818, -0.5       , -0.76604444, -0.93969262, -1.        ])

In [29]:
np.tan(c)

array([ 0.00000000e+00,  3.63970234e-01,  8.39099631e-01,  1.73205081e+00,
        5.67128182e+00, -5.67128182e+00, -1.73205081e+00, -8.39099631e-01,
       -3.63970234e-01, -1.22464680e-16])

In [33]:
#calculating the cot in the numpy 
1/np.tan(c)

C:\Users\Monu Verma\AppData\Local\Temp\ipykernel_40608\3325776137.py:2: RuntimeWarning: divide by zero encountered in divide
  1/np.tan(c)


array([            inf,  2.74747742e+00,  1.19175359e+00,  5.77350269e-01,
        1.76326981e-01, -1.76326981e-01, -5.77350269e-01, -1.19175359e+00,
       -2.74747742e+00, -8.16561968e+15])

#calculating the cosec theta in the numpy 
1/np.sin(c)

In [35]:
#calculating the sec in the numpy 
1/np.cos(c)

array([ 1.        ,  1.06417777,  1.30540729,  2.        ,  5.75877048,
       -5.75877048, -2.        , -1.30540729, -1.06417777, -1.        ])

### Inverse trigo functions 


In [36]:
#In numpy inverse trigno is measured iun arcfunction 

In [45]:
theta = np.linspace(0,1,10)#since most of the function range is 1 to -1 or other real numbers value should be taken carefully

In [44]:
np.arcsin(theta)

array([0.        , 0.11134101, 0.22409309, 0.33983691, 0.46055399,
       0.58903097, 0.72972766, 0.89112251, 1.09491408, 1.57079633])

In [46]:
np.arccos(theta)

array([1.57079633, 1.45945531, 1.34670323, 1.23095942, 1.11024234,
       0.98176536, 0.84106867, 0.67967382, 0.47588225, 0.        ])

In [47]:
np.arctan(theta)

array([0.        , 0.11065722, 0.21866895, 0.32175055, 0.41822433,
       0.5070985 , 0.5880026 , 0.66104317, 0.72664234, 0.78539816])

In [50]:
1/np.arctan(90)

np.float64(0.6411548284228251)

In [52]:
1/np.arcsin(0)

C:\Users\Monu Verma\AppData\Local\Temp\ipykernel_40608\2614299479.py:1: RuntimeWarning: divide by zero encountered in scalar divide
  1/np.arcsin(0)


np.float64(inf)