In [1]:
#exponents and logarithms 
import numpy as np 

In [4]:
#exponents 
x = np.array([1,2,3])
np.exp2(x)#give the squares of the numbers
np.power(3,x)#give the cube of the numbers 

array([ 3,  9, 27])

In [10]:
x = np.arange(1,11)
np.exp(x)
np.exp2(x)
np.power(3,x)
np.power(4,x)

array([      4,      16,      64,     256,    1024,    4096,   16384,
         65536,  262144, 1048576])

In [11]:
np.power(4,x)

array([      4,      16,      64,     256,    1024,    4096,   16384,
         65536,  262144, 1048576])

In [16]:
np.power(x,3)

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [13]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.power(x,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.power(x,10)

array([          1,        1024,       59049,     1048576,     9765625,
          60466176,   282475249,  1073741824,  3486784401, 10000000000])

In [27]:
#logarithms 
a = np.full((3,3),10**10)
np.log2(a)
np.log10(a)

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [28]:
np.log2(a)

array([[33.21928095, 33.21928095, 33.21928095],
       [33.21928095, 33.21928095, 33.21928095],
       [33.21928095, 33.21928095, 33.21928095]])

In [38]:
#logarithm for the small values
b= np.array([0.001,00.1,0.1,0.00001,0.11234])
np.expm1(b)

array([1.00050017e-03, 1.05170918e-01, 1.05170918e-01, 1.00000500e-05,
       1.18893220e-01])

In [39]:
np.log1p(b)

array([9.99500333e-04, 9.53101798e-02, 9.53101798e-02, 9.99995000e-06,
       1.06465904e-01])

### speciallized Ufuncs 

In [43]:
#gammma and beta in the scipy special

In [44]:
from scipy import special

In [48]:
# Function	Meaning
# erf(x)	Error function
# erfc(x)	Complement = 1 - erf(x)
# erfinv(y)	Inverse = finds the x that gives y
# The Gaussian curve describes how errors are distributed, and the area under the curve tells you the probability that the error falls within a chosen interval.

In [49]:
# Gamma    → Generalized factorial(n-1)![factorial]

# GammaLn  → Log of Gamma (avoids huge numbers like generalized facotrial of 1000000 it will will be greek god)

# Beta     → Special probability/statistics function