In [1]:
import numpy as np 

In [14]:
x = np.random.randint(10,size =(3,10))

In [15]:
x

array([[8, 0, 3, 2, 3, 2, 2, 7, 8, 9],
       [1, 7, 9, 2, 3, 8, 5, 3, 6, 7],
       [7, 9, 2, 0, 8, 5, 5, 8, 0, 3]], dtype=int32)

In [16]:
x[:1,:2]

array([[8, 0]], dtype=int32)

In [17]:
x[:2,:3]

array([[8, 0, 3],
       [1, 7, 9]], dtype=int32)

In [18]:
x[:3,:1]

array([[8],
       [1],
       [7]], dtype=int32)

In [19]:
x[:1,:1]

array([[8]], dtype=int32)

In [20]:
x[:,:]

array([[8, 0, 3, 2, 3, 2, 2, 7, 8, 9],
       [1, 7, 9, 2, 3, 8, 5, 3, 6, 7],
       [7, 9, 2, 0, 8, 5, 5, 8, 0, 3]], dtype=int32)

In [21]:
x[:,::2]

array([[8, 3, 3, 2, 8],
       [1, 9, 3, 5, 6],
       [7, 2, 8, 5, 0]], dtype=int32)

In [22]:
x[:,::-2]

array([[9, 7, 2, 2, 0],
       [7, 3, 8, 2, 7],
       [3, 8, 5, 0, 9]], dtype=int32)

In [25]:
x[2:,::-2]

array([[3, 8, 5, 0, 9]], dtype=int32)

In [26]:
x[2:,::]

array([[7, 9, 2, 0, 8, 5, 5, 8, 0, 3]], dtype=int32)

In [27]:
"Note - The array do not written the  copy but changing the slicing will change the orignal data so use copy method "

'Note - The array do not written the  copy but changing the slicing will change the orignal data so use copy method '

In [41]:
x_2 =x[0,:].copy()

In [42]:
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 7, 9, 2, 3, 8, 5, 3, 6, 7],
       [7, 9, 2, 0, 8, 5, 5, 8, 0, 3]], dtype=int32)

In [46]:
x_3 = x.copy()

In [47]:
x_3

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 7, 9, 2, 3, 8, 5, 3, 6, 7],
       [7, 9, 2, 0, 8, 5, 5, 8, 0, 3]], dtype=int32)

In [48]:
x_3[0,:] = 1

In [49]:
x_3[0,:]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

### Reshaping the arrays 

In [54]:
x = np.arange(1,10).reshape(3,3)

In [55]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
x_2 = np.arange(1,15).reshape(2,7)#elements must be fittable in the  give array size 

In [60]:
x_2

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])