# Important function in daily workflow

In [1]:
#using the some extra feature of the numpy ufuncs 

In [5]:
#very important function where we test multiple things and compare results according to what we need 
import numpy as np
array = np.array([1,2,3,4,5])
empty = np.empty(5)
trigo_func = np.sin(array,out=empty)

In [4]:
empty

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [7]:
empty_2 = np.empty(5)
cos_array = np.cos(array,out=empty_2)

In [8]:
empty_3 = np.empty(5)
tan_array = np.tan(array,out=empty_3)

In [14]:
empty#sin

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [15]:
empty_2#cos

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [16]:
empty_3#tan

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])