# Important function in daily workflow

In [1]:
#using the some extra feature of the numpy ufuncs 

In [5]:
#very important function where we test multiple things and compare results according to what we need 
import numpy as np
array = np.array([1,2,3,4,5])
empty = np.empty(5)
trigo_func = np.sin(array,out=empty)

In [4]:
empty

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [7]:
empty_2 = np.empty(5)
cos_array = np.cos(array,out=empty_2)

In [8]:
empty_3 = np.empty(5)
tan_array = np.tan(array,out=empty_3)

In [14]:
empty#sin

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [15]:
empty_2#cos

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [16]:
empty_3#tan

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

### aggregate

In [19]:
## A reduce repeatedly applies a given operation to the elements of an array until only a single result remains

In [20]:
a = np.arange(1,11)

In [21]:
a 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.add.reduce(a)

np.int64(55)

In [25]:
np.add.accumulate(a)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [26]:
np.multiply.reduce(a)

np.int64(3628800)

In [27]:
np.multiply.accumulate(a)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [ ]:
c = np.arange(1,6)

In [31]:
#outer function in the numpy 
d = np.arange(1,6)

In [35]:
#multiply the two arrays using the outer function of the numpy
np.multiply.outer(d,d)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [36]:
np.add.outer(d,d)

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [39]:
np.add

<ufunc 'add'>

In [41]:
np.add??

Signature:       np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\monu verma\searches\new folder\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is Tru

In [42]:
np.add.outer??

Docstring:
outer(A, B, /, **kwargs)

Apply the ufunc `op` to all pairs (a, b) with a in `A` and b in `B`.

Let ``M = A.ndim``, ``N = B.ndim``. Then the result, `C`, of
``op.outer(A, B)`` is an array of dimension M + N such that:

.. math:: C[i_0, ..., i_{M-1}, j_0, ..., j_{N-1}] =
   op(A[i_0, ..., i_{M-1}], B[j_0, ..., j_{N-1}])

For `A` and `B` one-dimensional, this is equivalent to::

  r = empty(len(A),len(B))
  for i in range(len(A)):
      for j in range(len(B)):
          r[i,j] = op(A[i], B[j])  # op = ufunc in question

Parameters
----------
A : array_like
    First array
B : array_like
    Second array
kwargs : any
    Arguments to pass on to the ufunc. Typically `dtype` or `out`.
    See `ufunc` for a comprehensive overview of all available arguments.

Returns
-------
r : ndarray
    Output array

See Also
--------
numpy.outer : A less powerful version of ``np.multiply.outer``
              that `ravel`\ s all inputs to 1D. This exists
              primarily for compatibili

In [19]:
import numpy as np
e = np.random.random(100)

In [23]:
np.sum(e)

np.float64(46.33260289991857)

In [26]:
np.sum(e)

np.float64(46.33260289991857)

In [ ]:
#checking the time of the big array and small array 
