In [2]:
"Numpy attributes"

'Numpy attributes'

In [48]:
import numpy as np 
np.random.seed()
#one dimensional array 
x1 = np.random.randint(10,size=6,dtype='int64')
#two dimensional array 
x2 = np.random.randint(293,size=(3,3))
#three dimensional array 
x3 = np.random.randint(12,size=(10,3,4))#contain multiple 2 dimensional array 

In [49]:
#ndim is function for getting to the know the no of dimension 
x1.ndim


1

In [50]:
x2.ndim

2

In [51]:
x3.ndim

3

In [52]:
x3 = np.random.randint(193,size=(100,34,3))

In [53]:
x3.ndim

3

In [54]:
x3

array([[[135,  41, 139],
        [130, 131,  43],
        [ 51,  49,  41],
        ...,
        [143, 159, 168],
        [ 12, 184, 122],
        [149,  54,  16]],

       [[ 26,  61, 150],
        [ 63,   6, 116],
        [ 32,  35,  31],
        ...,
        [152, 121, 177],
        [179,  74, 191],
        [ 83, 155,  15]],

       [[105, 159,   6],
        [189,  38,  91],
        [ 66,   5,  18],
        ...,
        [128,  71,  51],
        [ 93, 183,  10],
        [153, 100, 112]],

       ...,

       [[  5, 168, 147],
        [ 57, 173,  71],
        [ 61, 184,  74],
        ...,
        [ 23, 161,  28],
        [166,  73,  37],
        [ 27, 167, 167]],

       [[183,  29, 168],
        [161,  68, 172],
        [ 61, 184,  65],
        ...,
        [170, 158,  20],
        [ 91, 143, 163],
        [ 38,  73,  22]],

       [[177,   0, 124],
        [ 91, 180, 182],
        [ 98, 174, 161],
        ...,
        [ 31, 143, 146],
        [ 71,  48,  36],
        [ 67, 184, 112]]

In [55]:
x3.dtype

dtype('int32')

In [56]:
x2.dtype

dtype('int32')

In [58]:
x1.dtype#changed the data type from the  32 to 64

dtype('int64')

### Checking the memory consumption of different arrays

In [63]:
f"Item memo {x1.itemsize} bytes"

'Item memo 8 bytes'

In [64]:
x2.nbytes

36

In [65]:
x1.nbytes

48

In [66]:
"There is different nbyter for old the array"

'There is different nbyter for old the array'

In [68]:
x3.nbytes# most here "

40800

In [69]:
print(x1)

[0 0 0 0 0 5]


In [70]:
print(x1)

[0 0 0 0 0 5]


In [71]:
array = x1

In [72]:
array[0]

np.int64(0)

In [73]:
array[-1]

np.int64(5)

In [74]:
array[-1:0]

array([], dtype=int64)

In [75]:
array[:]

array([0, 0, 0, 0, 0, 5])

In [76]:
array[-1::1]

array([5])

In [77]:
array[-1:1]

array([], dtype=int64)

In [79]:
array[-1::-1]

array([5, 0, 0, 0, 0, 0])

In [80]:
array[-4]

np.int64(0)

In [81]:
array[-4] = 1

In [82]:
array

array([0, 0, 1, 0, 0, 5])

In [85]:
array[2] = 84007230

In [86]:
array

array([       0,        0, 84007230,        0,        0,        5])

In [88]:
x2

array([[179, 273,  57],
       [  2, 106, 255],
       [248, 205, 127]], dtype=int32)

In [90]:
x2[0,0:]

array([179, 273,  57], dtype=int32)

In [93]:
x2[1,2]

np.int32(255)

In [98]:
x1[0] = 2.3434343#this float here will reduce to the int even though we have given it the float value it adjust according the the datatypes 

In [97]:
x1

array([       2,        0, 84007230,        0,        0,        5])