In [1]:
import numpy as np 

In [2]:
x = np.random.randint(10,size =(3,10))

In [3]:
x

array([[9, 7, 8, 8, 7, 6, 3, 0, 9, 5],
       [8, 2, 8, 6, 4, 7, 5, 6, 2, 7],
       [2, 4, 2, 6, 3, 2, 0, 0, 1, 0]], dtype=int32)

In [4]:
x[:1,:2]

array([[9, 7]], dtype=int32)

In [5]:
x[:2,:3]

array([[9, 7, 8],
       [8, 2, 8]], dtype=int32)

In [6]:
x[:3,:1]

array([[9],
       [8],
       [2]], dtype=int32)

In [7]:
x[:1,:1]

array([[9]], dtype=int32)

In [8]:
x[:,:]

array([[9, 7, 8, 8, 7, 6, 3, 0, 9, 5],
       [8, 2, 8, 6, 4, 7, 5, 6, 2, 7],
       [2, 4, 2, 6, 3, 2, 0, 0, 1, 0]], dtype=int32)

In [9]:
x[:,::2]

array([[9, 8, 7, 3, 9],
       [8, 8, 4, 5, 2],
       [2, 2, 3, 0, 1]], dtype=int32)

In [10]:
x[:,::-2]

array([[5, 0, 6, 8, 7],
       [7, 6, 7, 6, 2],
       [0, 0, 2, 6, 4]], dtype=int32)

In [11]:
x[:,::-2]

array([[5, 0, 6, 8, 7],
       [7, 6, 7, 6, 2],
       [0, 0, 2, 6, 4]], dtype=int32)

In [12]:
x[2:,::]

array([[2, 4, 2, 6, 3, 2, 0, 0, 1, 0]], dtype=int32)

In [13]:
"Note - The array do not written the  copy but changing the slicing will change the orignal data so use copy method "

'Note - The array do not written the  copy but changing the slicing will change the orignal data so use copy method '

In [14]:
x_2 =x[0,:].copy()

In [15]:
x

array([[9, 7, 8, 8, 7, 6, 3, 0, 9, 5],
       [8, 2, 8, 6, 4, 7, 5, 6, 2, 7],
       [2, 4, 2, 6, 3, 2, 0, 0, 1, 0]], dtype=int32)

In [16]:
x_3 = x.copy()

In [17]:
x_3

array([[9, 7, 8, 8, 7, 6, 3, 0, 9, 5],
       [8, 2, 8, 6, 4, 7, 5, 6, 2, 7],
       [2, 4, 2, 6, 3, 2, 0, 0, 1, 0]], dtype=int32)

In [18]:
x_3[0,:] = 1

In [19]:
x_3[0,:]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

### Reshaping the arrays 

In [20]:
x = np.arange(1,10).reshape(3,3)

In [21]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
x_2 = np.arange(1,15).reshape(2,7)#elements must be fittable in the  give array size 

In [23]:
x_2

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [42]:
x_1 = np.eye(3,4).reshape(1,12)
x_1

array([[1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.]])

In [52]:
#changing the dimension of the array 
x = np.arange(1,13)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
x_column_matrix = x.reshape(12,1).copy()

In [55]:
x_column_matrix

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [58]:
x_2d = x.copy().reshape(2,6)

In [59]:
x_2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [61]:
x_3d = x.copy().reshape(3,4)

In [63]:
x_3d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
x_4d = x.copy().reshape(6,2)

In [65]:
x_4d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [69]:
y = np.array([[1,2,3],[1,2,3]])

In [70]:
y

array([[1, 2, 3],
       [1, 2, 3]])

In [71]:
y[:,np.newaxis]

array([[[1, 2, 3]],

       [[1, 2, 3]]])

In [72]:
y[np.newaxis,:]

array([[[1, 2, 3],
        [1, 2, 3]]])

In [73]:
#note point - note point is that np.newaxis work only to make row matrix and column matric reshape is a flexible method to do the things 

### Array Concatenation and Splitting
All of the preceding routines worked on single arrays. It’s also possible to combine
multiple arrays into one, and to conversely split a single array into multiple arrays.

In [80]:
x1 = np.random.randint(10,size =(2,3))
x2 = np.random.randint(10,size =(2,3))
x3 = np.random.randint(19000,size =(2,3))

In [88]:
#concatenating multiple array one can be at any limit 
print(np.concatenate([x1,x2,x3,x2,x3,x2,x1,x1]))#it is concatenated in the firsts exis which is a defalut exis by far 

[[    4     7     1]
 [    8     7     3]
 [    2     1     4]
 [    9     5     9]
 [ 6777  6488 10419]
 [12069 12987 16641]
 [    2     1     4]
 [    9     5     9]
 [ 6777  6488 10419]
 [12069 12987 16641]
 [    2     1     4]
 [    9     5     9]
 [    4     7     1]
 [    8     7     3]
 [    4     7     1]
 [    8     7     3]]


In [90]:
print(np.concatenate([x1,x2,x3,x2,x3,x2,x1,x1],axis=1))#concatenating in the axis = 1 

[[    4     7     1     2     1     4  6777  6488 10419     2     1     4
   6777  6488 10419     2     1     4     4     7     1     4     7     1]
 [    8     7     3     9     5     9 12069 12987 16641     9     5     9
  12069 12987 16641     9     5     9     8     7     3     8     7     3]]


In [91]:
#axis 0 means it is going downward - vertically 
#axis 1 means it is going sidebyside - horizontal 

In [97]:
#vstacking in numpy means vertical stacking 
a = np.arange(1,4)
a1 = np.random.randint(4,size=(2,3))

In [98]:
%xmode Verbose
print(np.vstack([a,a1]))

Exception reporting mode: Verbose
[[1 2 3]
 [3 2 0]
 [2 0 3]]


In [99]:
_

array([[[1, 2, 3],
        [1, 2, 3]]])

In [100]:
__

array([[[1, 2, 3],
        [1, 2, 3]]])

In [105]:
a2 = np.array([[99],[99]])

In [107]:
#hstact means stacking it horizontally and can be said that filling the value into available arrays 
print(np.hstack([a2,a1]))

[[99  3  2  0]
 [99  2  0  3]]


In [108]:
#note - dimension should be mathing when this function is applie either it will give error 