In [1]:
#chapter - 4 Linear algebra 
#vector is arrow in space so ofcourse it would have direction and also would have some value
#in its intial form vector position of the tail in the cartisian plane is 0,0 

In [2]:
#vector 
v = [2,3]

In [3]:
v

[2, 3]

In [4]:
#making an vecto array usin thenumpy
import numpy as np  
vector = np.array([2,3])

In [5]:
vector

array([2, 3])

In [6]:
#vector do looks like numbers stored but we have to remember that its aspect of direction and other thing so that
#vector are not only number but have different roles in different aspects of the work 

In [7]:
#a three dimensional vector means three direction 
vector_3d = np.array([1,2,3])

In [8]:
vector_3d

array([1, 2, 3])

In [9]:
vector_5d = np.array([1,2,3,4,5])#it does look like simple plain array but when we visual we will see how 5 direction will make it work

In [10]:
#addition of  two vectors  
v = np.array([1,2,3])
w = np.array([-1,-2,-3])
v+w

array([0, 0, 0])

In [11]:
#adding two vector is easy but it is different when we see it in cartesian plane

In [12]:
#adding  vector is commutative means it does not matter in which  order i have to perform the function

In [13]:
#scaling of the vector 

In [14]:
#multplying or dividing the vector for scalling the vector 
v*2

array([2, 4, 6])

In [15]:
v*1/2

array([0.5, 1. , 1.5])

In [16]:
v*10000

array([10000, 20000, 30000])

In [17]:
v/10000

array([0.0001, 0.0002, 0.0003])

In [18]:
#manipulatinng the vector basically means that we are manipulating the data in simple terms 

In [19]:
#span and linear Dependence
#the whole space of the possible vectors are called span 
#when we have to vectors in the different direction we call it linearly  independent and it can have unlimited possible vectors

In [20]:
#the possible number of vectors become limited when they co existing on the same line it limits the possible number of vectors and they can't have many more than this 

In [21]:
#but why do we care if there are limited or not limited i am thinkinng this now lets me see what comes next story is going good 

In [22]:
#Linear transformation

In [23]:
#according to the matric - [2,3] 2 is in the position of the i hat and j is in the position of the j hat 

In [24]:
#they are individual as [2,0] and [0,3] if we see that on the graph 

In [25]:
#if we increase or decrease we have  to remember that other things like sampling or span or scalling is going to be different as weel 

In [26]:
#it addition vector will also increase since the increase in the its vector 

In [27]:
#we can't have curve or other things  in the linear algebra because it is called linear algebra

In [28]:
#that's the simple ideas we have got till now of vectors or algebra in the perspective of the data or scalling or whatever we call it 

In [29]:
#matrix multiplication in  the pandas 
from numpy import array
basis = array([[1,2],[2,3]])

In [30]:
basis 

array([[1, 2],
       [2, 3]])

In [31]:
prod = array([1,2])

In [32]:
#multiplying both the vector 
mul = basis.dot(prod)

In [33]:
mul

array([5, 8])

In [34]:
#a more complicated vector transformation 


#declaring the i hat and j hat 
i_hat = array([2,1])
j_hat = array([2,-3])


#composing the vector and as well making the rows and the columns 
basis = array([i_hat , j_hat]).transpose()

In [35]:
#declaring the vector v  
v = array([2,1])


#making the 1 new vector using the product of the basis on the basis of the v 
new_vector = basis.dot(v)

In [36]:
new_vector

array([ 6, -1])

In [37]:
#combining two transformation 
import numpy as np 

#Tranformation - 1

#declaring the i_hat and j_hat 
i_hat1 = array([1,2])
j_hat1 = array([2,3])

#transforming the Tranformation - 1 
basis_1 = array([i_hat1,j_hat1]).transpose()

#Tranformation - 2 

#declaring the i_hat and j_hat 
i_hat2 = array([1,3])
j_hat2 = array([2,3])

#transforming the Transformation -2 
basis_2 = array([i_hat2 , j_hat2]).transpose()



#combining the two transpose or Transformation
combined = basis_1@basis_2  #@ - operator used for making the transform 

#declaring the vector 
v = array([1,1])

#making the new vector from the combined Transformation
new_vector = combined.dot(v)


In [38]:
new_vector

array([15, 24])

In [39]:
#this result can change according the which way will multiply so we can come to the conclusion they are not commutative but rather they will producce the different result when we change the direction 

In [40]:
#determinents 

In [41]:
#solving a determinent problem 
from numpy.linalg import det
from numpy import array

In [42]:
#declaring the array 
i_hat = array([2,3])
j_hat = array([3,4])
basis = array([i_hat,j_hat]).transpose()
det = det(basis)
det

np.float64(-1.0000000000000004)

In [43]:
from numpy.linalg import det
#negative determinent
i_hat1 = array([-2, 1])
j_hat2 = array([1, 2])
basis2 = array([i_hat1,j_hat2]).transpose()
det2 = det(basis2)

In [44]:
from numpy.linalg import det
#a squished area transformed determinent 
i_hat2 = array([1,0])
j_hat2 = array([0,1])
basis3 = array([i_hat2,j_hat2])
det = det(basis3)

In [45]:
#lets starts todays work 

In [46]:
#special type of the matrixes 

In [47]:
#inverse matrix - unoding the transformation by other matrix and the multiplication of the matrix and also the inverse matrix it becomes indentity matrix 

In [48]:
#sparse matrix - sparse matrix is type of the matrix where we have matrix which have the majority of the values as the 0  

In [49]:
#using numpy to solve these type of equation basically of the inverse and indentity matrix 

In [51]:
#making a inverse matrix and the indentity matrix using the logic of the system of the equation 
from sympy import *


#4x + 2y + 4z = 44
#5x + 3y + 7z = 56
#9x + 3y + 6z = 72

A=Matrix([
 [4, 2, 4],
 [5, 3, 7],
 [9, 3, 6]
])


#making a inverse of the matrix 
inverse = A.inv()

#so the multiplication of the matrix and its inverse is identity matrix according the proof of the algebra 
ide